"""add engine fields

Revision ID: 04acfa28ed04
Revises: 
Create Date: 2026-02-27 14:51:00.746237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04acfa28ed04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('engine_version', sa.String(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('engine_result', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('quiz_attempts', 'recommended_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('recommended_products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('quiz_attempts', 'engine_result')
    op.drop_column('quiz_attempts', 'engine_version')
    # ### end Alembic commands ###
